version: '3.6'


services:

    # Backend API
    smart-brain-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /c/Users/maiji/Desktop/smart-brain-api
        environment: 
            POSTGRES_URI: postgres
        links: 
            - postgres
        ports:
            - "3000:3000"
        volumes:
            - ./:/c/Users/maiji/Desktop/smart-brain-api

    # Postgres
    postgres:
        environment: 
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-barin-docker
            POSTGRES_HOST: postgres
        container_name: postgres
        image: postgres
        ports: 
            - "5432:5432"